// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "./components/Navigation";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export const viewport = {
  themeColor: "#938d85",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main className="content">{children}</main>
        <Navigation />
      </body>
    </html>
  );
}
